/**
 * NeoCode — Matrix Scene Image Embedder
 *
 * Converts any image (PNG/JPG/WebP) into embedded pixel data for the
 * startup screen. Uses `sharp` (already in project deps) for decoding.
 *
 * Usage:
 *   bun scripts/embed-scene-image.ts <path/to/image.png>
 *
 * Output:
 *   src/assets/matrixScene.ts  — TypeScript constant with 8-level
 *                                palette pixel data at 78×32 px
 *
 * After running, the startup screen automatically uses the embedded
 * pixel data instead of the procedural generation.
 */

import sharp from 'sharp'
import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// ── Target dimensions ────────────────────────────────────────────────────────
// 78 × 32 → 78 terminal chars × 16 display rows (half-block technique)
// At Sixel render, each pixel is upscaled 8× → 624 × 256
const TARGET_W = 78
const TARGET_H = 32

// ── 8-level Matrix green palette ─────────────────────────────────────────────
// Level 0 = black void, Level 7 = peak #00ff41
// Maps input luminosity → palette index
const LEVELS = 8

function luminosityToLevel(r: number, g: number, b: number): number {
  // Perceptual luminosity (ITU-R BT.709)
  const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
  // Map 0-255 → 0-(LEVELS-1)
  return Math.min(LEVELS - 1, Math.floor((lum / 255) * LEVELS))
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const inputPath = process.argv[2]
  if (!inputPath) {
    console.error('Usage: bun scripts/embed-scene-image.ts <image-path>')
    console.error('Example: bun scripts/embed-scene-image.ts docs/mockups/matrix-ref.png')
    process.exit(1)
  }

  const absInput = resolve(inputPath)
  console.log(`Reading: ${absInput}`)

  // Resize to TARGET_W × TARGET_H, force 3-channel RGB
  const { data, info } = await sharp(absInput)
    .resize(TARGET_W, TARGET_H, {
      fit: 'fill',
      kernel: 'lanczos3',
    })
    .toColorspace('srgb')
    .raw()
    .toBuffer({ resolveWithObject: true })

  console.log(`Decoded: ${info.width}×${info.height} (${info.channels}ch)`)

  // Build palette-indexed pixel string: one char per pixel ('0'-'7')
  const pixels: string[] = []
  const channels = info.channels  // 3 (RGB) or 4 (RGBA)
  for (let i = 0; i < TARGET_W * TARGET_H; i++) {
    const r = data[i * channels]!
    const g = data[i * channels + 1]!
    const b = data[i * channels + 2]!
    pixels.push(luminosityToLevel(r, g, b).toString())
  }

  const pixelStr = pixels.join('')

  // Generate TypeScript output
  const ts = `// AUTO-GENERATED by scripts/embed-scene-image.ts — do not edit manually
// Source image: ${absInput}
// Dimensions: ${TARGET_W}×${TARGET_H} pixels, 8-level Matrix green palette (0=black, 7=peak)
//
// Each character is a palette index ('0'–'7') for one pixel, row-major order.
// Row length = ${TARGET_W}, total rows = ${TARGET_H}, total pixels = ${TARGET_W * TARGET_H}

export const SCENE_W = ${TARGET_W}
export const SCENE_H = ${TARGET_H}
export const SCENE_PIXELS = '${pixelStr}'
`

  const outPath = resolve(ROOT, 'src', 'assets', 'matrixScene.ts')
  writeFileSync(outPath, ts, 'utf-8')
  console.log(`Written: ${outPath}`)
  console.log(`Pixel data: ${pixelStr.length} chars (~${(pixelStr.length / 1024).toFixed(1)}KB)`)
  console.log()
  console.log('Rebuild to apply:')
  console.log('  bun run build')
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
